server:
  port: 8080
spring:
  datasource:
    # mysql
#    url: jdbc:mysql://127.0.0.1:3306/h2?useUnicode=true&characterEncoding=UTF-8
#    username: h2admin
#    password: H2admin
#    driver-class-name: com.mysql.cj.jdbc.Driver
    # pgsql
    url: jdbc:postgresql://127.0.0.1:5432/h2
    username: h2admin
    password: H2admin
    driver-class-name: org.postgresql.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 8
      max-active: 8
      max-wait: 30000
      default-auto-commit: true
      filter:
        # sql stat
        stat:
          enabled: false
          log-slow-sql: false
          slow-sql-millis: 50
  redis:
    host: 127.0.0.1
    port: 6379
    password: foobared
    lettuce:
      pool:
        max-active: 8
        min-idle: 4
        max-idle: 8
        max-wait: 30000
      shutdown-timeout: 100
  jackson:
    date-format: 'yyyy-MM-dd HH:mm:ss'

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true


breeze:
  deploy-mode: cluster